using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using System.Text;

namespace MyGenerator;

/// <summary>
/// Source generator that detects classes marked with [GenerateInfo] and generates
/// a companion static class exposing compile-time information about the marked type.
/// </summary>
[Generator]
public class MyGeneratorImpl : IIncrementalGenerator
{
    private const string AttributeNamespace = "MyGenerator.Attributes";
    private const string AttributeName = "GenerateInfoAttribute";
    private const string AttributeSource = """
        // <auto-generated/>
        namespace MyGenerator.Attributes;

        /// <summary>
        /// Apply this attribute to a class to generate a companion info class.
        /// </summary>
        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
        public sealed class GenerateInfoAttribute : System.Attribute { }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the attribute declaration into every compilation
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateInfoAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // Collect all class declarations annotated with [GenerateInfo]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetMarkedClass(ctx))
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(classDeclarations, static (spc, classes) =>
        {
            if (classes.IsDefaultOrEmpty)
                return;

            foreach (var classInfo in classes)
            {
                if (classInfo is not null)
                    GenerateInfoClass(spc, classInfo);
            }
        });
    }

    private static MarkedClassInfo? GetMarkedClass(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;

        foreach (var attributeList in classDecl.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (ctx.SemanticModel.GetSymbolInfo(attribute).Symbol is not IMethodSymbol attributeSymbol)
                    continue;

                var attributeType = attributeSymbol.ContainingType;
                if (attributeType.ToDisplayString() == $"{AttributeNamespace}.{AttributeName}")
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is INamedTypeSymbol typeSymbol)
                        return new MarkedClassInfo(typeSymbol);
                }
            }
        }

        return null;
    }

    private static void GenerateInfoClass(SourceProductionContext context, MarkedClassInfo classInfo)
    {
        var namespaceName = classInfo.Namespace;
        var className = classInfo.ClassName;
        var propertyCount = classInfo.PropertyCount;
        var methodCount = classInfo.MethodCount;

        var namespaceDecl = namespaceName.Length > 0 ? $"namespace {namespaceName};\n\n" : string.Empty;
        var typeName = namespaceName.Length > 0 ? $"{namespaceName}.{className}" : className;

        var source = $$"""
            // <auto-generated/>
            #nullable enable

            {{namespaceDecl}}/// <summary>
            /// Auto-generated companion class for <see cref="{{className}}"/>.
            /// Contains compile-time information about the source type.
            /// </summary>
            public static class {{className}}Info
            {
                /// <summary>The fully-qualified name of the source type.</summary>
                public const string TypeName = "{{typeName}}";

                /// <summary>The simple name of the source type.</summary>
                public const string ClassName = "{{className}}";

                /// <summary>The namespace that contains the source type.</summary>
                public const string Namespace = "{{namespaceName}}";

                /// <summary>The number of public properties on the source type.</summary>
                public const int PropertyCount = {{propertyCount}};

                /// <summary>The number of public methods on the source type.</summary>
                public const int MethodCount = {{methodCount}};

                /// <summary>Returns a human-readable summary of the source type.</summary>
                public static string GetSummary() =>
                    $"Type: {TypeName}, Properties: {PropertyCount}, Methods: {MethodCount}";
            }
            """;

        context.AddSource($"{className}Info.g.cs", SourceText.From(source, Encoding.UTF8));
    }

//#if (IsNetStandard20)
    private sealed class MarkedClassInfo : System.IEquatable<MarkedClassInfo>
    {
        public INamedTypeSymbol TypeSymbol { get; }

        public MarkedClassInfo(INamedTypeSymbol typeSymbol)
        {
            TypeSymbol = typeSymbol;
            Namespace = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : typeSymbol.ContainingNamespace.ToDisplayString();
            ClassName = typeSymbol.Name;
            PropertyCount = typeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Count(p => p.DeclaredAccessibility == Accessibility.Public);
            MethodCount = typeSymbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Count(m => m.DeclaredAccessibility == Accessibility.Public
                            && m.MethodKind == MethodKind.Ordinary);
        }

        public string Namespace { get; }
        public string ClassName { get; }
        public int PropertyCount { get; }
        public int MethodCount { get; }

        public bool Equals(MarkedClassInfo? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return SymbolEqualityComparer.Default.Equals(TypeSymbol, other.TypeSymbol);
        }

        public override bool Equals(object? obj) => Equals(obj as MarkedClassInfo);

        public override int GetHashCode() => SymbolEqualityComparer.Default.GetHashCode(TypeSymbol);

        public static bool operator ==(MarkedClassInfo? left, MarkedClassInfo? right) =>
            left is null ? right is null : left.Equals(right);

        public static bool operator !=(MarkedClassInfo? left, MarkedClassInfo? right) => !(left == right);
    }
//#else
    private sealed record MarkedClassInfo(INamedTypeSymbol TypeSymbol)
    {
        public string Namespace { get; } = TypeSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : TypeSymbol.ContainingNamespace.ToDisplayString();

        public string ClassName { get; } = TypeSymbol.Name;

        public int PropertyCount { get; } = TypeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Count(p => p.DeclaredAccessibility == Accessibility.Public);

        public int MethodCount { get; } = TypeSymbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Count(m => m.DeclaredAccessibility == Accessibility.Public
                            && m.MethodKind == MethodKind.Ordinary);
    }
//#endif
}
